(add-hook 'c-mode-common-hook '(lambda () (c-toggle-hungry-state 1)))
(setq c-default-style "linux"
      c-basic-offset 4)


;; Compilation
(global-set-key (kbd "<f5>") (lambda ()
                               (interactive)
                               (setq-local compilation-read-command nil)
                               (call-interactively 'compile)))
(global-set-key (kbd "<f6>") 'next-error)
(global-set-key (kbd "<f7>") 'previous-error)
(global-set-key (kbd "<f8>") 'ggtags-find-file)



(semantic-mode 1)

(semantic-add-system-include "/vendor/windriver/vxworks/target/usr/h/" 'c-mode)
(semantic-add-system-include "/vendor/windriver/vxworks/target/h" 'c-mode)
(semantic-add-system-include "/vendor/windriver/vxworks/target/usr/h/c++" 'c++-mode)
(semantic-add-system-include "/vendor/ibm/Rhapsody/Share/LangCpp" 'c++-mode)

(semantic-add-system-include "/app/h" 'c-mode)
(semantic-add-system-include "/app/common/h" 'c-mode)
(semantic-add-system-include "/app/oamp/anm/h" 'c-mode)
(semantic-add-system-include "/app/video/h" 'c-mode)
(semantic-add-system-include "/app/video/erm/h" 'c-mode)
(semantic-add-system-include "/app/video/dcam/h" 'c-mode)
(semantic-add-system-include "/app/video/rsm/h" 'c-mode)
(semantic-add-system-include "/app/video/mpegMgr/h" 'c-mode)
(semantic-add-system-include "/app/video/mpegTask/h" 'c-mode)
(semantic-add-system-include "/app/video/common/h" 'c-mode)
(semantic-add-system-include "/app/video/encryption/caMsgLib/h" 'c-mode)
(semantic-add-system-include "/app/video/encryption/vpme_eqm/h" 'c-mode)
(semantic-add-system-include "/app/video/encryption/vpme_scg/h" 'c-mode)
(semantic-add-system-include "/app/common/ipc/h" 'c-mode)
(semantic-add-system-include "/app/common/util/h" 'c-mode)
(semantic-add-system-include "/app/common/anmShl/h" 'c-mode)
(semantic-add-system-include "/app/common/mtceMonitor/h" 'c-mode)
(semantic-add-system-include "/app/common/config/h" 'c-mode)
(semantic-add-system-include "/app/common/rsh/h" 'c-mode)
(semantic-add-system-include "/app/common/ntp/h" 'c-mode)
(semantic-add-system-include "/app/common/uml/h" 'c-mode)
(semantic-add-system-include "/app/oamp/h" 'c-mode)
(semantic-add-system-include "/app/oamp/uml/h" 'c-mode)
(semantic-add-system-include "/app/oamp/mtce/h" 'c-mode)
(semantic-add-system-include "/app/oamp/running_config/h" 'c-mode)
(semantic-add-system-include "/app/dcam/h" 'c-mode)
(semantic-add-system-include "/app/rsm/h" 'c-mode)
(semantic-add-system-include "/app/ucam/h" 'c-mode)
(semantic-add-system-include "/app/card/h" 'c-mode)
(semantic-add-system-include "/app/cli/rccbd/h" 'c-mode)
(semantic-add-system-include "/kernel/h" 'c-mode)
(semantic-add-system-include "/kernel/kernelCli/h" 'c-mode)
(semantic-add-system-include "/kernel/loader/h" 'c-mode)
(semantic-add-system-include "/kernel/srvc/board/h" 'c-mode)
(semantic-add-system-include "/kernel/srvc/upstream/h" 'c-mode)
(semantic-add-system-include "/kernel/srvc/downstream/h" 'c-mode)
(semantic-add-system-include "/kernel/srvc/fabric/h" 'c-mode)
(semantic-add-system-include "/kernel/srvc/common/h" 'c-mode)
(semantic-add-system-include "/kernel/sdvrpc/h" 'c-mode)
(semantic-add-system-include "/kernel/syscall/h" 'c-mode)
(semantic-add-system-include "/kernel/kernelUtils/h" 'c-mode)

(semantic-add-system-include "/vendor/windriver/components/ip_net2/ipcom/include" 'c-mode)
(semantic-add-system-include "/vendor/windriver/components/ip_net2/ipcom/port/include" 'c-mode)
(semantic-add-system-include "/vendor/windriver/components/ip_net2/ipnet2/include" 'c-mode)

(require 'company-c-headers)
(add-to-list 'company-c-headers-path-system "/vendor/windriver/vxworks/target/h")
(add-to-list 'company-c-headers-path-system "/vendor/windriver/vxworks/target/usr/h/")
(add-to-list 'company-c-headers-path-system "/vendor/windriver/vxworks/target/usr/h/c++/")
(add-to-list 'company-c-headers-path-system "/vendor/ibm/Rhapsody/Share/LangCpp")

(add-to-list 'company-c-headers-path-system "/app/h")
(add-to-list 'company-c-headers-path-system "/app/common/h")
(add-to-list 'company-c-headers-path-system "/app/oamp/anm/h")
(add-to-list 'company-c-headers-path-system "/app/video/h")
(add-to-list 'company-c-headers-path-system "/app/video/erm/h")
(add-to-list 'company-c-headers-path-system "/app/video/dcam/h")
(add-to-list 'company-c-headers-path-system "/app/video/rsm/h")
(add-to-list 'company-c-headers-path-system "/app/video/mpegMgr/h")
(add-to-list 'company-c-headers-path-system "/app/video/mpegTask/h")
(add-to-list 'company-c-headers-path-system "/app/video/common/h")
(add-to-list 'company-c-headers-path-system "/app/video/encryption/caMsgLib/h")
(add-to-list 'company-c-headers-path-system "/app/video/encryption/vpme_eqm/h")
(add-to-list 'company-c-headers-path-system "/app/video/encryption/vpme_scg/h")
(add-to-list 'company-c-headers-path-system "/app/common/ipc/h")
(add-to-list 'company-c-headers-path-system "/app/common/util/h")
(add-to-list 'company-c-headers-path-system "/app/common/anmShl/h")
(add-to-list 'company-c-headers-path-system "/app/common/mtceMonitor/h")
(add-to-list 'company-c-headers-path-system "/app/common/config/h")
(add-to-list 'company-c-headers-path-system "/app/common/rsh/h")
(add-to-list 'company-c-headers-path-system "/app/common/ntp/h")
(add-to-list 'company-c-headers-path-system "/app/common/uml/h")
(add-to-list 'company-c-headers-path-system "/app/oamp/h")
(add-to-list 'company-c-headers-path-system "/app/oamp/uml/h")
(add-to-list 'company-c-headers-path-system "/app/oamp/mtce/h")
(add-to-list 'company-c-headers-path-system "/app/oamp/running_config/h")
(add-to-list 'company-c-headers-path-system "/app/dcam/h")
(add-to-list 'company-c-headers-path-system "/app/rsm/h")
(add-to-list 'company-c-headers-path-system "/app/ucam/h")
(add-to-list 'company-c-headers-path-system "/app/router/h")
(add-to-list 'company-c-headers-path-system "/app/card/h")
(add-to-list 'company-c-headers-path-system "/app/cli/rccbd/h")

(add-to-list 'company-c-headers-path-system "/kernel/h")
(add-to-list 'company-c-headers-path-system "/kernel/kernelCli/h")
(add-to-list 'company-c-headers-path-system "/kernel/kernelUtils/h")
(add-to-list 'company-c-headers-path-system "/kernel/srvc/board/h")
(add-to-list 'company-c-headers-path-system "/kernel/srvc/upstream/h")
(add-to-list 'company-c-headers-path-system "/kernel/srvc/downstream/h")
(add-to-list 'company-c-headers-path-system "/kernel/srvc/fabric/h")
(add-to-list 'company-c-headers-path-system "/kernel/srvc/common/h")
(add-to-list 'company-c-headers-path-system "/kernel/sdvrpc/h")

(add-to-list 'company-c-headers-path-system "/vendor/windriver/components/ip_net2/ipcom/include")
(add-to-list 'company-c-headers-path-system "/vendor/windriver/components/ip_net2/ipcom/port/include")
(add-to-list 'company-c-headers-path-system "/vendor/windriver/components/ip_net2/ipnet2/include")
(add-to-list 'company-c-headers-path-system "/vendor/windriver/components/ip_net2/iptcp/include")
