#!/bin/bash
umask 022
set -o emacs
VIMPATH=/usr/bin/vim

if [[ "$OSTYPE" = "cygwin" ]] ;  then
    if [[ "$SHELL" == "/bin/bash" ]]; then
        set -o igncr
    fi

    export VIM_PATH=vim

    if [[ -s "$HOME/.arris/arris.env" ]] ; then source "$HOME/.arris/arris.env" ; fi

    if [[ ! -z $SETVIEW_ENV ]] ;  then
        if [[ $SETVIEW_ENV = "C4" ]] ;  then
            export TAGFILES="/CMTS/sw/src/src.t,/CMTS/sw/include/h.t,/model/cmts/model.t,/common/windriver/build/kernel.t,/common/ezchip/ezchip.t, /CMTS/sw/Rhapsody/Share/LangCpp/oxf/rhap.t"
        elif [[ $SETVIEW_ENV = "E6" ]] ;  then
            export TAGFILES="/app/app.t,/kernel/kernel.t,/system/system.t,/vendor/windriver/vxworks/target/wrs.t,/vendor/windriver/components/comp.t,/devTools/videosim/videosim.t"
        fi
    fi

    set -o emacs
elif [[ "$OSTYPE" == "linux-gnu" ]]; then
    export EDITOR=vim
    add_to_path PATH $HOME/bin:/usr/local/bin:/usr/atria/bin
    #if [[ -x /usr/atria/bin/cleartool ]]; then
        #PS1="\[\033[1;34m\][$(cleartool pwv -s) \w]$\[\033[0m\] "
        trap 'printf "\033]0;$HOSTNAME: $(cleartool pwv -s) %s\007" "${BASH_COMMAND//[^[:print:]]/}"' DEBUG
    #fi
		# Calculate the view name for later use
		VIEW=`echo $CLEARCASE_ROOT  | sed -e 's./view/..g'`

		PS1="\[\033[1;32m\][$VIEW]\[\033[1;34m\][\u@\h:\w]$\[\033[0m\] "

		export CCASE_BLD_UMASK=002
		export CCASE_MAKE_COMPAT=gnu
    set -o emacs
else
    export TERM="xterm-256color"

    VIM_PATH=vim
    add_to_path PATH $HOME/bin:/usr/local/bin:/usr/atria/bin
    add_to_path LD_LIBRARY_PATH /usr/local/lib
    add_to_path MANPATH /usr/local/man:/usr/man

	# No need to setup build environment if not in a view
	if [[ -z "$CLEARCASE_ROOT" ]] ;   then
		PS1="\[\033[1;34m\][\u@\h:\w]$\[\033[0m\] "
	else
		# Calculate the view name for later use
		VIEW=`echo $CLEARCASE_ROOT  | sed -e 's./view/..g'`

		PS1="\[\033[1;32m\][$VIEW]\[\033[1;34m\][\u@\h:\w]$\[\033[0m\] "

		export CCASE_BLD_UMASK=002
		export CCASE_MAKE_COMPAT=gnu
	fi

    if [[ "$OSTYPE" = "solaris2.10" ]] ;  then
        export WIND_BASE=/vobs/tornadonew/mips211solaris
        export WIND_HOST_TYPE=sun4-solaris2
        export PATH=${WIND_BASE}/host/sun4-solaris2/bin:${PATH}

        VIMPATH=/usr/local/bin/vim
        # Call this to use old gryphon montavista
        add_gryphon_sbtools() {
            eval `/vobs/gryphon/linux/Montavista/add_mvtools sh "$@"`
        }

        # Call this to use new C3_3rdparty montavista
        add_3rd_sbtools() {
            eval `/vobs/C3_3rdparty/linux/Montavista/add_mvtools sh "$@"`
        }
        if [[ ! -z "$CLEARCASE_ROOT" ]]; then
            add_3rd_sbtools bash sb1-elf-2.7.16
        fi
    fi

fi
if [[ ! -z "$VIM_PATH" ]] ;  then
    export VIEWER="$VIM_PATH" 
    export EDITOR="$VIM_PATH"
fi
hostify bash_profile
