#!/bin/bash
umask 022
VIMPATH=/usr/bin/vim
if [[ "$OSTYPE" = "cygwin" ]] ;  then
    if [[ "$SHELL" == "/bin/bash" ]]; then
        set -o igncr
    fi

    export VIM_PATH=vim

    if [[ ! -z $SETVIEW_ENV ]] ;  then
        if [[ $SETVIEW_ENV = "C4" ]] ;  then
            export TAGFILES="/CMTS/sw/src/src.t,/CMTS/sw/include/h.t,/model/cmts/model.t,/common/windriver/build/kernel.t,/common/ezchip/ezchip.t, /CMTS/sw/Rhapsody/Share/LangCpp/oxf/rhap.t"
        elif [[ $SETVIEW_ENV = "E6" ]] ;  then
            export TAGFILES="/app/app.t,/kernel/kernel.t,/system/system.t,/vendor/windriver/vxworks/target/wrs.t,/vendor/windriver/components/comp.t,/devTools/videosim/videosim.t"
        fi
    fi
elif [[ "$OSTYPE" == "linux-gnu" ]]; then
    export EDITOR=vim
    add_to_path PATH $HOME/bin:/usr/local/bin:/usr/atria/bin
    if shopt -q login_shell; then
        if [[ -x /usr/atria/bin/cleartool ]]; then
            trap 'printf "\033]0;$HOSTNAME: $(cleartool pwv -s) %s\007" "${BASH_COMMAND//[^[:print:]]/}"' DEBUG
        else
            trap 'printf "\033]0;$HOSTNAME: %s\007" "${BASH_COMMAND//[^[:print:]]/}"' DEBUG
        fi
    fi
    # Calculate the view name for later use
    VIEW=`echo $CLEARCASE_ROOT  | sed -e 's./view/..g'`
    git_branch_prompt() {
        BRANCH=$(git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/')
        if [[ "X$BRANCH" != "X" ]]; then
            top_level=$(git rev-parse --show-toplevel)
            echo " ${BRANCH} on $(basename $top_level)"
        fi
    }

    PS1="\[\e[31m\] \u@\h \[\e[m\]\[\e[35m\] \w \[\e[m\]"

    BRANCH=$( git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/')
    if [[ "X$VIEW" != "X" ]]; then
        PS1="\[\e[32m\] $VIEW \[\e[m\]$PS1"
    fi
    PS1="\[\e[33m\]\$(git_branch_prompt)\[\e[m\]$PS1"
    PS1="\[\e[39m\] \D{%T} \[\e[m\]$PS1"
    PS1="\[\e[0;31m\]┌─\e[0m\e[34m{\[\e[0m\e[0;32m\]$PS1\e[34m}\n\[\e[0;31m\]└─>\[\e[0m\] "

    export CCASE_BLD_UMASK=002
    export CCASE_MAKE_COMPAT=gnu
else
    export TERM="xterm-256color"

    VIM_PATH=vim
    add_to_path PATH $HOME/bin:/usr/local/bin:/usr/atria/bin
    add_to_path LD_LIBRARY_PATH /usr/local/lib
    add_to_path MANPATH /usr/local/man:/usr/man

	# No need to setup build environment if not in a view
	if [[ -z "$CLEARCASE_ROOT" ]] ;   then
		PS1="\[\033[1;34m\][\u@\h:\w]$\[\033[0m\] "
	else
		# Calculate the view name for later use
		VIEW=`echo $CLEARCASE_ROOT  | sed -e 's./view/..g'`

		PS1="\[\033[1;32m\][$VIEW]\[\033[1;34m\][\u@\h:\w]$\[\033[0m\] "

		export CCASE_BLD_UMASK=002
		export CCASE_MAKE_COMPAT=gnu
	fi

    if [[ "$OSTYPE" = "solaris2.10" ]] ;  then
        export WIND_BASE=/vobs/tornadonew/mips211solaris
        export WIND_HOST_TYPE=sun4-solaris2
        export PATH=${WIND_BASE}/host/sun4-solaris2/bin:${PATH}

        VIMPATH=/usr/local/bin/vim
        # Call this to use old gryphon montavista
        add_gryphon_sbtools() {
            eval `/vobs/gryphon/linux/Montavista/add_mvtools sh "$@"`
        }

        # Call this to use new C3_3rdparty montavista
        add_3rd_sbtools() {
            eval `/vobs/C3_3rdparty/linux/Montavista/add_mvtools sh "$@"`
        }
        if [[ ! -z "$CLEARCASE_ROOT" ]]; then
            add_3rd_sbtools bash sb1-elf-2.7.16
        fi
    fi

fi
if [[ ! -z "$VIM_PATH" ]] ;  then
    export VIEWER="$VIM_PATH" 
    export EDITOR="$VIM_PATH"
fi

shopt -s histappend
shopt -u checkwinsize
export GOPATH=$HOME/.go

if [[ "$OSTYPE" = "cygwin" ]] ;  then
    if [[ -s "$HOME/.arris/arris.env" ]] ; then source "$HOME/.arris/arris.env" ; fi
fi
set -o emacs
export ARRIS_TOOLS_DIR=//irlcor-fil01/Projects/E6000/swDevTools 

export LESSGLOBALTAGS=global

hostify bash_profile
