#!/bin/bash
function hostify()
{
    local RC=$1
    if [[ -e ~/.bash.d/$RC.$(hostname) ]]; then
        source ~/.bash.d/$RC.$(hostname)
    fi
    if [[ ! -z "$CC_VIEW_SPEC" ]]; then
        if [[ -e ~/.bash.d/$RC.clearcase ]]; then
            source ~/.bash.d/$RC.clearcase
        fi
    fi
}

function add_to_path
{
    if [[ "${!1}" =~ "(^|:)"${2}"(:|$)" ]]
    then
        return 0
    fi
    export $1="$2:${!1}"
}

function ps1() 
{ 
    GREEN='\[\033[0;32;1m\]'
    BLUE='\[\033[0;36;1m\]'

    PS1="\[\e[7m\]\[\e[0m\]${GREEN}\[\e[1m\]\W\[\e[0m\] \!\$\[\e[0m\] "
}

function fgrep()
{
    case $# in 
        1)
            DIR=.
            EXPR=$1
            ;;
        2)
            DIR=$1
            EXPR=$2
            ;;
        *)
            echo "Usage: $0 [directory] <expression>"
            return 1;
            ;;
    esac

    find ${DIR} -type d -path obj -prune -o -type f -name \*[cph]   | xargs egrep "$EXPR"
}

function figrep()
{
    case $# in 
        1)
            DIR=.
            EXPR=$1
            ;;
        2)
            DIR=$1
            EXPR=$2
            ;;
        *)
            echo "Usage: $0 [directory] <expression>"
            return 1;
            ;;
    esac

    find ${DIR} -type d -path obj -prune -o -type f -name \*[cph]   | xargs egrep -i "$EXPR"
}

function vi()
{
    case $OSTYPE in
        cygwin*)
            GVIM="/c/Program Files (x86)/Vim/vim73/gvim.exe"
            ;;
        *)
            GVIM=gvim
            ;;
    esac

    "${GVIM}" --servername ${SETVIEW_ENV-GVIM} --remote-tab-silent "${@}"&
}

function title()
{
    echo -ne "\033]2;$*\007"
}

#function settitle()
#{
#    if [[ -z "$CC_VIEW_SPEC" ]]; then
#        title "$HOSTNAME :: $PWD"
#    else
#        title "$(cleartool pwv -s) :: $HOSTNAME :: $PWD :: "
#    fi
#}
#export PROMPT_COMMAND=settitle

hostify bash_funcs
