#!/bin/bash

# polybar
if [[ ! -x ./polybar/build/bin/polybar ]]; then
    echo Polybar
    cd polybar
    rm -rf build
    mkdir build
    cd build
    cmake -DCMAKE_INSTALL_PREFIX=/usr/local ..
    make -j8 && sudo make install
    cd ../..
fi
 
# i3-gaps
if [[ ! -x ./i3/i3 ]]; then
    echo i3
    cd i3
    autoreconf --force --install
    rm -rf build
    mkdir build
    cd build
    ../configure --prefix=/usr/local --sysconfdir=/etc
    make -j8 &&  sudo make install
    cd ../..
fi

# rofi
if [[ ! -x ./rofi/build/rofi ]]; then
    echo rofi
    cd rofi
    autoreconf --force --install
    rm -rf build
    mkdir build
    cd build
    ../configure --prefix=/usr/local --sysconfdir=/etc --disable-check
    make -j8
    sudo make install
fi
