#!/bin/bash

# polybar
if [[ ! -x ./polybar/build/bin/polybar ]]; then
    echo Polybar
    cd polybar
    git submodule init
    git submodule update
    rm -rf build
    mkdir build
    cd build
    cmake -DCMAKE_INSTALL_PREFIX=/usr/local .. && sudo make install
    cd ../..
fi
 
# i3-gaps
if [[ ! -x ./i3/i3 ]]; then
    echo i3
    cd i3
    make && sudo make install
    cd ..
fi

# rofi
if [[ ! -x ./rofi/build/rofi ]]; then
    echo rofi
    cd rofi
    git submodule init
    git submodule update
    autoreconf --force --install
    rm -rf build
    mkdir build
    cd build
    ../configure --prefix=/usr/local --sysconfdir=/etc --disable-check
    make
    sudo make install
fi
